version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: realestate-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: RealEstateDB
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./scripts/init-mongodb.js:/docker-entrypoint-initdb.d/init-mongodb.js:ro
    networks:
      - realestate-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: realestate-api
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - MongoDbSettings__ConnectionString=mongodb://mongodb:27017
      - MongoDbSettings__DatabaseName=RealEstateDB
      - MongoDbSettings__OwnersCollectionName=Owners
      - MongoDbSettings__PropertiesCollectionName=Properties
      - MongoDbSettings__PropertyImagesCollectionName=PropertyImages
      - MongoDbSettings__PropertyTracesCollectionName=PropertyTraces
      - CorsOrigins=http://localhost:3000,http://localhost:5173
      - Logging__LogLevel__Default=Information
      - Logging__LogLevel__Microsoft.AspNetCore=Warning
    ports:
      - "5000:80"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - realestate-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

networks:
  realestate-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
